# Generated by Django 5.0.6 on 2026-06-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('on_hand', models.IntegerField()),
                ('avg_daily_demand', models.FloatField()),
                ('lead_time_days', models.IntegerField()),
                ('safety_stock', models.IntegerField()),
                ('unit_cost_eur', models.FloatField()),
                ('last_delivery_date', models.DateField()),
                ('risk', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('ok', 'Ok')], default='ok', max_length=16)),
                ('risk_score', models.FloatField(default=0.0)),
                ('action_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['risk_score'],
            },
        ),
    ]
